<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8645c66ee28fb5548b7433d02b967b75
{
    public static $files = array (
        'f0b0a0ce17c165a6177a60461ed0476d' => __DIR__ . '/../../..' . '/app/src/Helper/Functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'ArubaSPA\\HiSpeedCache\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ArubaSPA\\HiSpeedCache\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/src',
        ),
    );

    public static $classMap = array (
        'ArubaSPA\\HiSpeedCache\\Admin\\AdminAssets' => __DIR__ . '/../../..' . '/app/src/Admin/AdminAssets.php',
        'ArubaSPA\\HiSpeedCache\\Admin\\AdminBar' => __DIR__ . '/../../..' . '/app/src/Admin/AdminBar.php',
        'ArubaSPA\\HiSpeedCache\\Admin\\AdminNotice' => __DIR__ . '/../../..' . '/app/src/Admin/AdminNotice.php',
        'ArubaSPA\\HiSpeedCache\\Admin\\AdminSettingPage' => __DIR__ . '/../../..' . '/app/src/Admin/AdminSettingPage.php',
        'ArubaSPA\\HiSpeedCache\\Admin\\Ajax\\CacheCleaner' => __DIR__ . '/../../..' . '/app/src/Admin/Ajax/CacheCleaner.php',
        'ArubaSPA\\HiSpeedCache\\Admin\\SiteHealth' => __DIR__ . '/../../..' . '/app/src/Admin/SiteHealth.php',
        'ArubaSPA\\HiSpeedCache\\ArubaHispeedCache' => __DIR__ . '/../../..' . '/app/src/ArubaHispeedCache.php',
        'ArubaSPA\\HiSpeedCache\\CacheWarmer\\Ajax\\CacheWarmer' => __DIR__ . '/../../..' . '/app/src/CacheWarmer/Ajax/CacheWarmer.php',
        'ArubaSPA\\HiSpeedCache\\CacheWarmer\\CacheWarmerManager' => __DIR__ . '/../../..' . '/app/src/CacheWarmer/CacheWarmerManager.php',
        'ArubaSPA\\HiSpeedCache\\Container\\ContainerBuilder' => __DIR__ . '/../../..' . '/app/src/Container/ContainerBuilder.php',
        'ArubaSPA\\HiSpeedCache\\Container\\ParamiterBag' => __DIR__ . '/../../..' . '/app/src/Container/ParamiterBag.php',
        'ArubaSPA\\HiSpeedCache\\Core\\ActionLinks' => __DIR__ . '/../../..' . '/app/src/Core/ActionLinks.php',
        'ArubaSPA\\HiSpeedCache\\Core\\I18n' => __DIR__ . '/../../..' . '/app/src/Core/I18n.php',
        'ArubaSPA\\HiSpeedCache\\Core\\Requirements' => __DIR__ . '/../../..' . '/app/src/Core/Requirements.php',
        'ArubaSPA\\HiSpeedCache\\Core\\ServiceCheck' => __DIR__ . '/../../..' . '/app/src/Core/ServiceCheck.php',
        'ArubaSPA\\HiSpeedCache\\Core\\Setup' => __DIR__ . '/../../..' . '/app/src/Core/Setup.php',
        'ArubaSPA\\HiSpeedCache\\Events\\AbstractEvents' => __DIR__ . '/../../..' . '/app/src/Events/AbstractEvents.php',
        'ArubaSPA\\HiSpeedCache\\Events\\BulkActionManager' => __DIR__ . '/../../..' . '/app/src/Events/BulkActionManager.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Comments\\PurgeProxyCacheOnDeletedComment' => __DIR__ . '/../../..' . '/app/src/Events/Comments/PurgeProxyCacheOnDeletedComment.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Comments\\PurgeProxyCacheOnNewComment' => __DIR__ . '/../../..' . '/app/src/Events/Comments/PurgeProxyCacheOnNewComment.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Comments\\PurgeProxyCacheTransitionCommentStatus' => __DIR__ . '/../../..' . '/app/src/Events/Comments/PurgeProxyCacheTransitionCommentStatus.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Deferred\\PurgeProxyCacheInDeferredMode' => __DIR__ . '/../../..' . '/app/src/Events/Deferred/PurgeProxyCacheInDeferredMode.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Plugins\\AbstractPluginEvent' => __DIR__ . '/../../..' . '/app/src/Events/Plugins/AbstractPluginEvent.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Plugins\\PurgeProxyCacheOnActivatedPlugin' => __DIR__ . '/../../..' . '/app/src/Events/Plugins/PurgeProxyCacheOnActivatedPlugin.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Plugins\\PurgeProxyCacheOnDeactivatedPlugin' => __DIR__ . '/../../..' . '/app/src/Events/Plugins/PurgeProxyCacheOnDeactivatedPlugin.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Plugins\\PurgeProxyCacheOnDeletePlugin' => __DIR__ . '/../../..' . '/app/src/Events/Plugins/PurgeProxyCacheOnDeletePlugin.php',
        'ArubaSPA\\HiSpeedCache\\Events\\PostType\\PurgeProxyCacheOnPostUpdated' => __DIR__ . '/../../..' . '/app/src/Events/PostType/PurgeProxyCacheOnPostUpdated.php',
        'ArubaSPA\\HiSpeedCache\\Events\\PostType\\PurgeProxyCacheOnTransitionStatus' => __DIR__ . '/../../..' . '/app/src/Events/PostType/PurgeProxyCacheOnTransitionStatus.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Term\\PurgeProxyCacheOnDeleteTerm' => __DIR__ . '/../../..' . '/app/src/Events/Term/PurgeProxyCacheOnDeleteTerm.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Term\\PurgeProxyCacheOnEditNavMenu' => __DIR__ . '/../../..' . '/app/src/Events/Term/PurgeProxyCacheOnEditNavMenu.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Term\\PurgeProxyCacheOnEditTerm' => __DIR__ . '/../../..' . '/app/src/Events/Term/PurgeProxyCacheOnEditTerm.php',
        'ArubaSPA\\HiSpeedCache\\Events\\Themes\\PurgeProxyCacheOnSwitchTheme' => __DIR__ . '/../../..' . '/app/src/Events/Themes/PurgeProxyCacheOnSwitchTheme.php',
        'ArubaSPA\\HiSpeedCache\\HeartBeat\\HeartBeatLimiter' => __DIR__ . '/../../..' . '/app/src/HeartBeat/HeartBeatLimiter.php',
        'ArubaSPA\\HiSpeedCache\\Helper\\AdminNotice' => __DIR__ . '/../../..' . '/app/src/Helper/AdminNotice.php',
        'ArubaSPA\\HiSpeedCache\\Purger\\AbstractPurger' => __DIR__ . '/../../..' . '/app/src/Purger/AbstractPurger.php',
        'ArubaSPA\\HiSpeedCache\\Purger\\WpPurger' => __DIR__ . '/../../..' . '/app/src/Purger/WpPurger.php',
        'ArubaSPA\\HiSpeedCache\\Request\\Request' => __DIR__ . '/../../..' . '/app/src/Request/Request.php',
        'ArubaSPA\\HiSpeedCache\\Settings\\MigrationsManagers' => __DIR__ . '/../../..' . '/app/src/Settings/MigrationsManagers.php',
        'ArubaSPA\\HiSpeedCache\\Settings\\RegisterSettings' => __DIR__ . '/../../..' . '/app/src/Settings/RegisterSettings.php',
        'ArubaSPA\\HiSpeedCache\\Traits\\HasContainer' => __DIR__ . '/../../..' . '/app/src/Traits/HasContainer.php',
        'ArubaSPA\\HiSpeedCache\\Traits\\Instance' => __DIR__ . '/../../..' . '/app/src/Traits/Instance.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8645c66ee28fb5548b7433d02b967b75::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8645c66ee28fb5548b7433d02b967b75::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8645c66ee28fb5548b7433d02b967b75::$classMap;

        }, null, ClassLoader::class);
    }
}
